// Generated by CoffeeScript 1.3.1
(function() {
  var date, date_format, img, k, params, prev_weight, today, url, v, weight, weights, weights_data, x;

  weights = {
    "2012-05-17": 79.8,
    "2012-05-18": 79.6,
    "2012-05-19": 78.9
  };

  date_format = function(d) {
    var date, month, year;
    d = new Date(d);
    year = d.getFullYear();
    month = d.getMonth() + 1;
    date = d.getDate();
    if (("" + month).length === 1) {
      month = "0" + month;
    }
    if (("" + date).length === 1) {
      date = "0" + date;
    }
    return "" + year + "-" + month + "-" + date;
  };

  prev_weight = 0;

  today = new Date;

  weights_data = (function() {
    var _i, _ref, _results;
    _results = [];
    for (x = _i = 0; _i < 30; x = ++_i) {
      date = date_format(new Date(today.getTime() - x * 24 * 60 * 60 * 1000));
      weight = (_ref = weights[date]) != null ? _ref : prev_weight;
      _results.push(prev_weight = weight);
    }
    return _results;
  })();

  url = 'http://chart.apis.google.com/chart';

  params = {
    'cht=': 'lc',
    'chls=': 5,
    'chco=': '76A4FB',
    'chm=': 'B,C3D9FF66,0,0,0',
    'chs=': '1000x300',
    'chd=t:': weights_data.reverse()
  };

  params = ((function() {
    var _results;
    _results = [];
    for (k in params) {
      v = params[k];
      _results.push("" + k + v);
    }
    return _results;
  })()).join('&');

  img = $('<img/>').attr({
    src: "" + url + "?" + params
  });

  $(function() {
    return img.appendTo('body');
  });

}).call(this);
